# Generated by Django 5.1.4 on 2025-01-13 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_image', models.ImageField(upload_to='originals/%Y/%m/%d/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/%Y/%m/%d/')),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('file_size', models.IntegerField(null=True)),
                ('file_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
